### ISSUE TITLE
Errors encountered in keyboardmap; not compiled

### ISSUE THREAD

**Issue by uurcan7** [hexvalid/Linux-CapsLock-Delay-Fixer#20] opened 2022-07-07 00:40 UTC
diyezuurca@diyezuurca-HP-Laptop-15-db1xxx:~$ bash -ic "sh /home/diyezuurca/İndirilenler/u7cldf/bootstrap.sh"

syntax error: line 1391 of keyboardmap
last scanned symbol is: type
Errors encountered in keyboardmap; not compiled.
/
diyezuurca@diyezuurca-HP-Laptop-15-db1xxx:~$ bash "/home/diyezuurca/İndirilenler/u7cldf/bootstrap.sh"

syntax error: line 1391 of keyboardmap
last scanned symbol is: type
Errors encountered in keyboardmap; not compiled.

**Comment by ahobsonsayers** [comment] 2022-07-20 16:54
This seems like a duplicate of #19

**Closed** 2023-11-21 23:06 UTC
